import asyncio
from decimal import Decimal

from sqlalchemy import select, text

from app.core.db import SessionFactory, engine
from app.modules.events.models import Event, EventStream, RegistrationType

OFFICIAL_EVENTS = [
    {
        "slug": "hackathon",
        "name": "Hackathon 36",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 4,
        "prize_amount": Decimal("50000"),
        "venue": "Innovation Lab",
        "fee": "₹500 / team",
        "day": 1,
        "time": "09:00 — 21:00",
        "rules": [
            "Teams of 2–4 members",
            "No pre-built solutions allowed",
            "All code must be written during the event",
            "Use of open-source libraries is permitted",
        ],
        "eligibility": "Open to all college students across India",
        "description": "A 36-hour hackathon where teams build solutions to real-world challenges. Mentors, APIs and unlimited coffee provided.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "ctf",
        "name": "Capture The Flag",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 2,
        "prize_amount": Decimal("25000"),
        "venue": "Cyber Arena",
        "fee": "₹300 / team",
        "day": 2,
        "time": "10:00 — 18:00",
        "rules": [
            "Solo or teams of 2",
            "No brute-force attacks on infrastructure",
            "Flag sharing results in disqualification",
        ],
        "eligibility": "Open to all students",
        "description": "Jeopardy-style CTF with challenges spanning cryptography, reverse engineering, web exploitation and forensics.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "code-relay",
        "name": "Code Relay",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 3,
        "team_size_max": 3,
        "prize_amount": Decimal("15000"),
        "venue": "Lab Complex",
        "fee": "₹250 / team",
        "day": 1,
        "time": "14:00 — 17:00",
        "rules": [
            "Teams of 3",
            "Each round is timed",
            "Standard competitive programming rules apply",
        ],
        "eligibility": "Open to all college students",
        "description": "A relay-style competitive programming challenge. Each team member solves one problem before passing to the next.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "ai-arena",
        "name": "AI Arena",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 3,
        "prize_amount": Decimal("20000"),
        "venue": "Innovation Lab",
        "fee": "₹300 / team",
        "day": 2,
        "time": "09:00 — 16:00",
        "rules": [
            "Teams of 1–3",
            "Pre-trained models allowed with attribution",
            "Final presentation required",
        ],
        "eligibility": "Open to all students with ML experience",
        "description": "Build and deploy an AI model to solve a surprise dataset challenge. Judged on accuracy, creativity and presentation.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "battle-of-bands",
        "name": "Battle of the Bands",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.team,
        "team_size_min": 4,
        "team_size_max": 8,
        "prize_amount": Decimal("30000"),
        "venue": "Main Stage",
        "fee": "₹400 / band",
        "day": 2,
        "time": "18:00 — 22:00",
        "rules": [
            "4–8 members per band",
            "15-minute set per band",
            "Bands must bring their own instruments",
            "Sound check at 16:00",
        ],
        "eligibility": "Open to all",
        "description": "Bands compete in an electrifying live performance showdown. Original compositions and covers both welcome.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "street-art",
        "name": "Street Art Championship",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 2,
        "prize_amount": Decimal("15000"),
        "venue": "Campus Grounds",
        "fee": "₹150 / entry",
        "day": 1,
        "time": "10:00 — 16:00",
        "rules": [
            "Solo or duo",
            "Theme-based — revealed at start",
            "All materials provided",
            "No pre-made stencils",
        ],
        "eligibility": "Open to all students",
        "description": "Transform blank walls into masterpieces. Theme revealed on the day. Materials provided.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "poetry-slam",
        "name": "Poetry Slam",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "team_size_min": None,
        "team_size_max": None,
        "prize_amount": Decimal("10000"),
        "venue": "Amphitheatre",
        "fee": "Free Entry",
        "day": 3,
        "time": "11:00 — 14:00",
        "rules": [
            "Solo performance",
            "3-minute time limit per piece",
            "Original works only",
            "No props or costumes",
        ],
        "eligibility": "Open to all students",
        "description": "Spoken word and poetry performances judged on content, delivery and audience response.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "valorant",
        "name": "Valorant Championship",
        "stream": EventStream.gaming,
        "registration_type": RegistrationType.team,
        "team_size_min": 5,
        "team_size_max": 6,
        "prize_amount": Decimal("25000"),
        "venue": "Esports Arena",
        "fee": "₹500 / team",
        "day": 1,
        "time": "10:00 — 20:00",
        "rules": [
            "Teams of 5 + 1 substitute",
            "Standard competitive rules",
            "Anti-cheat required",
            "Match disputes handled by tournament officials",
        ],
        "eligibility": "Open to all",
        "description": "5v5 competitive Valorant tournament. Double elimination bracket with live commentary.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "bgmi",
        "name": "BGMI Showdown",
        "stream": EventStream.gaming,
        "registration_type": RegistrationType.team,
        "team_size_min": 4,
        "team_size_max": 4,
        "prize_amount": Decimal("20000"),
        "venue": "Esports Arena",
        "fee": "₹400 / squad",
        "day": 2,
        "time": "10:00 — 18:00",
        "rules": [
            "Squads of 4",
            "Official devices only (no emulators)",
            "Multiple rounds with aggregate scoring",
        ],
        "eligibility": "Open to all",
        "description": "Squad-based BGMI tournament with multiple rounds. Points-based scoring across all matches.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "pitch-perfect",
        "name": "Pitch Perfect",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 4,
        "prize_amount": Decimal("40000"),
        "venue": "Conference Hall",
        "fee": "Free Entry",
        "day": 3,
        "time": "09:00 — 15:00",
        "rules": [
            "Teams of 1–4",
            "10-minute pitch + 5-minute Q&A",
            "Slide deck required",
            "Working prototype is a plus",
        ],
        "eligibility": "Open to all students and recent graduates",
        "description": "Pitch your startup idea to a panel of investors, entrepreneurs and industry experts. The best pitches win seed funding.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "sustainability-hack",
        "name": "Sustainability Hack",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 4,
        "prize_amount": Decimal("20000"),
        "venue": "Green Lab",
        "fee": "Free Entry",
        "day": 1,
        "time": "09:00 — 17:00",
        "rules": [
            "Teams of 2–4",
            "Problem statements provided on day",
            "Prototype or detailed plan required",
        ],
        "eligibility": "Open to all students",
        "description": "Design solutions for real environmental and social challenges. Judged on feasibility, management and innovation.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "dance-battle",
        "name": "Dance Battle",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 12,
        "prize_amount": Decimal("20000"),
        "venue": "Main Stage",
        "fee": "₹200 / entry",
        "day": 2,
        "time": "15:00 — 18:00",
        "rules": [
            "Solo: 3-minute performance",
            "Crew (4–12): 8-minute performance",
            "Props allowed but not required",
            "Music tracks submitted in advance",
        ],
        "eligibility": "Open to all students",
        "description": "Freestyle and choreographed dance face-offs. Solo and crew categories. All styles welcome.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "robowars",
        "name": "Robowars: Steel Rite",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 3,
        "team_size_max": 5,
        "prize_amount": Decimal("120000"),
        "venue": "Arena 02 · East Yard",
        "fee": "₹600 / bot team",
        "day": 2,
        "time": "08:00 — 18:00",
        "rules": [
            "15kg weight limit excluding transmitter",
            "Failsafe cutoff mechanism mandatory",
            "Weapon lockout bars required in staging pits",
            "Double elimination knockout format",
        ],
        "eligibility": "Engineering and polytechnic colleges",
        "description": "15kg combat class. Reinforced arena, open pneumatic and spinner weapon rules, and an indestructible steel perimeter.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "silent-circuit",
        "name": "Silent Circuit",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 2,
        "prize_amount": Decimal("25000"),
        "venue": "Electronics Lab · B Wing",
        "fee": "₹200 / team",
        "day": 2,
        "time": "14:00 — 17:00",
        "rules": [
            "2-person team format",
            "Only provided lab instruments allowed",
            "First team to extract the correct hex payload wins",
        ],
        "eligibility": "Open to all engineering students",
        "description": "Reverse-engineer a sealed mystery PCB with zero schematics or documentation. Digital oscilloscopes and logic analyzers provided.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "mainstage-night-one",
        "name": "Mainstage: Night One",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "team_size_min": None,
        "team_size_max": None,
        "prize_amount": Decimal("0"),
        "venue": "Central Amphitheatre",
        "fee": "Included with Festival Pass",
        "day": 2,
        "time": "21:00 — 00:30",
        "rules": [
            "Valid festival registration or band required",
            "Gates lock at 21:00 sharp",
            "Zero prohibited substances permitted on amphitheatre turf",
        ],
        "eligibility": "All VYUHAM pass holders",
        "description": "The premier headline audio-visual concert. Forty thousand watts of immersive acoustic pressure under the open Thiruvananthapuram night.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "nritya",
        "name": "Nritya — Classical Frame",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 2,
        "prize_amount": Decimal("60000"),
        "venue": "Heritage Hall",
        "fee": "₹250 / entry",
        "day": 1,
        "time": "17:00 — 20:00",
        "rules": [
            "Solo or duet format",
            "Maximum performance duration: 10 minutes",
            "Traditional costumes and authentic acoustic tracks required",
        ],
        "eligibility": "Open to all verified college dancers",
        "description": "Classical Indian dance (Bharatanatyam, Mohiniyattam, Kuchipudi, Kathak) staged inside an architectural shadow lighting grid.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "street-battle",
        "name": "Street Battle 2v2",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 2,
        "prize_amount": Decimal("80000"),
        "venue": "Open Plaza",
        "fee": "₹300 / duo",
        "day": 3,
        "time": "15:00 — 19:00",
        "rules": [
            "2 vs 2 format",
            "No choreography allowed; raw freestyle only",
            "Judged by international panel",
        ],
        "eligibility": "Open to all street dancers",
        "description": "2v2 all-styles street dance battle. Live DJ rotation, unexpected beat drops, and raw cypher eliminations.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "retro-arcade",
        "name": "Retro Cabinet Run",
        "stream": EventStream.gaming,
        "registration_type": RegistrationType.solo,
        "team_size_min": None,
        "team_size_max": None,
        "prize_amount": Decimal("15000"),
        "venue": "Arcade Zone",
        "fee": "₹100 / entry",
        "day": 3,
        "time": "11:00 — 16:00",
        "rules": [
            "Solo speedrunners only",
            "Standard arcade stick controls",
            "Live leaderboard synced to auditorium display",
        ],
        "eligibility": "Open to all arcade enthusiasts",
        "description": "Twenty restored CRT arcade cabinets. Highest cumulative score across five retro speedrun classics. One coin credit per stage.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "impact-summit",
        "name": "Impact Summit",
        "stream": EventStream.management,
        "registration_type": RegistrationType.solo,
        "team_size_min": None,
        "team_size_max": None,
        "prize_amount": Decimal("100000"),
        "venue": "Convention Hall",
        "fee": "Free Entry (RSVP Required)",
        "day": 2,
        "time": "10:30 — 13:00",
        "rules": [
            "Interactive Q&A participation",
            "Networking round for startup founders and investors",
        ],
        "eligibility": "Founders, students, researchers",
        "description": "Keynote summit bringing together climate technologists, venture partners, and policy researchers solving real urban challenges.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "climate-build-sprint",
        "name": "Climate Build Sprint",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 4,
        "prize_amount": Decimal("100000"),
        "venue": "Green Lab",
        "fee": "₹300 / team",
        "day": 3,
        "time": "09:00 — 17:00",
        "rules": [
            "Teams of 2–4 members",
            "Solution must address one of three municipal challenge briefs",
            "Working prototype or simulation required",
        ],
        "eligibility": "Open to all students",
        "description": "Eight-hour rapid intervention sprint using live municipal weather and power sensor datasets. Judged on operational deployability.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "outreach-1000-hands",
        "name": "Outreach: 1000 Hands",
        "stream": EventStream.management,
        "registration_type": RegistrationType.solo,
        "team_size_min": None,
        "team_size_max": None,
        "prize_amount": Decimal("0"),
        "venue": "City Sector 4",
        "fee": "Free Volunteer Entry",
        "day": 1,
        "time": "06:30 — 10:00",
        "rules": [
            "Protective gear provided at staging desk",
            "Community service certificate awarded upon completion",
        ],
        "eligibility": "Open to all volunteers",
        "description": "Pre-dawn social impact and ecological restoration campaign across Technocity corridors with partner non-profits.",
        "featured": False,
        "status": "upcoming",
    },
]


async def main() -> None:
    async with SessionFactory() as session:
        # Clean up legacy placeholder events and streams before ORM loading
        try:
            await session.execute(text("DELETE FROM events WHERE name LIKE 'Placeholder%'"))
            await session.execute(text("UPDATE events SET stream = 'culture' WHERE stream::text = 'cultural'"))
            await session.execute(text("UPDATE events SET stream = 'gaming' WHERE stream::text = 'esports'"))
            await session.commit()
        except Exception as e:
            await session.rollback()
            print(f"Legacy cleanup note: {e}")

        # Check existing events by slug or name
        result = await session.scalars(select(Event))
        existing_events = list(result)
        existing_by_slug = {e.slug: e for e in existing_events if e.slug}
        existing_by_name = {e.name: e for e in existing_events}

        for item in OFFICIAL_EVENTS:
            slug = item["slug"]
            name = item["name"]
            existing = existing_by_slug.get(slug) or existing_by_name.get(name)

            if existing:
                for k, v in item.items():
                    setattr(existing, k, v)
            else:
                session.add(Event(**item))

        await session.commit()
        print(f"Successfully seeded {len(OFFICIAL_EVENTS)} official Vyuham '26 events.")
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
