import asyncio
from decimal import Decimal
from sqlalchemy import select, text
from app.core.db import SessionFactory, engine
from app.modules.events.models import Event, EventStream, RegistrationType
from app.modules.announcements.models import Announcement

OFFICIAL_EVENTS = [
    # ── DAY 1: OCTOBER 30, 2026 ──
    {
        "slug": "hackathon",
        "name": "Hackathon — 24HR",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 4,
        "prize_amount": Decimal("30000"),
        "venue": "Main Hall + Computer Lab",
        "fee": "₹1,000 per team",
        "day": 1,
        "time": "9:00 AM – 9:00 AM (DAY 2)",
        "rules": [
            "Theme: Agentic AI / Autonomous Systems",
            "24 hours continuous overnight building",
            "Midnight mentoring round and refreshments in Main Hall",
            "Jury demo and code evaluation on Day 2 morning",
        ],
        "eligibility": "Open to all students and developers across India",
        "description": "Theme: Agentic AI / Autonomous Systems. 24-hour hackathon, overnight build.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "best-manager",
        "name": "Best Manager",
        "stream": EventStream.management,
        "registration_type": RegistrationType.solo,
        "team_size_min": 1,
        "team_size_max": 1,
        "prize_amount": Decimal("15000"),
        "venue": "Gallery Hall",
        "fee": "₹200",
        "day": 1,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Individual executive assessment format",
            "Rounds: Aptitude screening, spontaneous crisis simulation, and board interview",
            "Evaluated by industry business leaders",
        ],
        "eligibility": "Undergraduate and postgraduate students",
        "description": "Aptitude, crisis management & leadership interview.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "best-management-team",
        "name": "Best Management Team",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 3,
        "team_size_max": 4,
        "prize_amount": Decimal("20000"),
        "venue": "Gallery Hall",
        "fee": "₹400",
        "day": 1,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Team-based business strategy simulation",
            "Case presentation, financial viability analysis, and live defense",
        ],
        "eligibility": "Open to college teams",
        "description": "Team-based business strategy evaluation.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "marketing-game",
        "name": "Marketing Game",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 4,
        "prize_amount": Decimal("15000"),
        "venue": "Gallery Hall",
        "fee": "₹400",
        "day": 1,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Product design and go-to-market execution challenge",
            "Viral campaign simulation and consumer pitch evaluation",
        ],
        "eligibility": "Open to all students",
        "description": "Product & campaign strategy simulation.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "finance-game",
        "name": "Finance Game",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 3,
        "prize_amount": Decimal("15000"),
        "venue": "Gallery Hall",
        "fee": "₹400",
        "day": 1,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Corporate crisis scenario with budget allocation and financial auditing",
            "Live market volatility decision-making rounds",
        ],
        "eligibility": "Open to all students",
        "description": "Simulated crisis — risk, budget & strategy.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "hr-game",
        "name": "HR Game",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 3,
        "prize_amount": Decimal("15000"),
        "venue": "Gallery Hall",
        "fee": "₹400",
        "day": 1,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Structured rounds: Debates, HR crossword, organizational minefield, and case studies",
            "Workplace mediation and executive conflict resolution",
        ],
        "eligibility": "Open to all students",
        "description": "Debates, HR crossword, minefield & case studies.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "business-quiz",
        "name": "Business Quiz",
        "stream": EventStream.management,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 2,
        "prize_amount": Decimal("10000"),
        "venue": "Gallery Hall",
        "fee": "₹200",
        "day": 1,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Teams of 2 participants",
            "Written preliminary round followed by live on-stage finals",
            "Focus: Corporate history, global markets, sports business, and brand strategies",
        ],
        "eligibility": "Open to all college students",
        "description": "Current affairs, sports & management rounds.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "panel-responsible-ai",
        "name": "Panel: Responsible AI — A Humanities Lens",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Seminar Hall",
        "fee": "Free Entry",
        "day": 1,
        "time": "10:00 AM – 11:30 AM",
        "rules": ["Interactive Q&A open to all fest attendees", "Venue seating on first-come basis"],
        "eligibility": "Open to all delegates",
        "description": "Keynote panel exploring AI ethics, humanities perspectives, and societal governance.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "talk-quantum-computing",
        "name": "Talk: Quantum Computing Meets AI: Real vs. Hype",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Seminar Hall",
        "fee": "Free Entry",
        "day": 1,
        "time": "12:00 PM – 1:30 PM",
        "rules": ["Open expert session", "Audience Q&A at the conclusion"],
        "eligibility": "Open to all delegates",
        "description": "In-depth talk by leading researchers separating quantum fact from marketing hype.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "workshop-prompt-engineering",
        "name": "Hands-on Workshop: Prompt Engineering & Building with LLMs (BYOD)",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Computer Lab",
        "fee": "Free Entry",
        "day": 1,
        "time": "2:00 PM – 3:30 PM",
        "rules": ["Bring Your Own Device (BYOD)", "Practical exercises with modern LLM frameworks"],
        "eligibility": "Open to all registered students",
        "description": "Hands-on workshop building practical applications with state-of-the-art LLMs.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "inauguration-ceremony",
        "name": "Inauguration Ceremony",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Open Air Stage",
        "fee": "Free Entry",
        "day": 1,
        "time": "5:00 PM",
        "rules": ["Official opening ceremony of VYUHAM ’26 on the Main Stage"],
        "eligibility": "Open to all delegates and dignitaries",
        "description": "Official opening of VYUHAM ’26 · Main Stage.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "hackathon-continues",
        "name": "Hackathon Continues",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "prize_amount": Decimal("0"),
        "venue": "Main Hall",
        "fee": "Hackathon Teams",
        "day": 1,
        "time": "Overnight",
        "rules": ["Overnight coding and prototype construction", "Mentorship access throughout the night"],
        "eligibility": "Registered 24HR Hackathon squads",
        "description": "Midnight mentoring round & snacks in the Main Hall.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "play-fest",
        "name": "Play Fest",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Campus Grounds",
        "fee": "Free Entry",
        "day": 1,
        "time": "Day One",
        "rules": ["Open interactive recreation and entertainment stalls"],
        "eligibility": "Open to all attendees",
        "description": "Entertainment zone running across campus.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "fitness-competition",
        "name": "Fitness Competition",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Campus Grounds",
        "fee": "₹50 per head",
        "day": 1,
        "time": "Day One",
        "rules": ["Stamina, endurance, and calisthenics challenge", "Individual leaderboard scoring"],
        "eligibility": "Open to all attendees",
        "description": "Campus fitness and stamina championship.",
        "featured": False,
        "status": "upcoming",
    },

    # ── DAY 2: OCTOBER 31, 2026 ──
    {
        "slug": "hackathon-demos",
        "name": "Hackathon Demos & Judging",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "prize_amount": Decimal("0"),
        "venue": "Main Hall",
        "fee": "Hackathon Teams",
        "day": 2,
        "time": "9:00 AM – 11:00 AM",
        "rules": ["Open floor prototype demos to evaluation panel", "Q&A and technical architecture inspection"],
        "eligibility": "24HR Hackathon participants",
        "description": "Open floor demonstrations to the jury.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "ctf",
        "name": "Capture the Flag",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 4,
        "prize_amount": Decimal("15000"),
        "venue": "Computer Lab",
        "fee": "₹400",
        "day": 2,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Jeopardy-style CTF challenge",
            "Categories: Web, Cryptography, Reverse Engineering, Forensics, and Binary Exploitation",
            "Strict anti-sharing and infrastructure safety rules",
        ],
        "eligibility": "Open to all student operatives",
        "description": "Cybersecurity puzzles and challenges.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "startup-showcase",
        "name": "Startup Showcase",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 4,
        "prize_amount": Decimal("15000"),
        "venue": "Gallery Hall",
        "fee": "₹400",
        "day": 2,
        "time": "10:00 AM – 5:00 PM",
        "rules": ["Founder pitch to expert jury", "Slide deck and working prototype demonstration required"],
        "eligibility": "Student startups and early-stage founders",
        "description": "Founders pitch to a panel of experts.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "prompt-war",
        "name": "Prompt War",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 2,
        "prize_amount": Decimal("15000"),
        "venue": "Computer Lab",
        "fee": "₹400",
        "day": 2,
        "time": "10:00 AM – 5:00 PM",
        "rules": [
            "Speed-prompting and output precision benchmark",
            "Evaluated on prompt structure, zero-shot/few-shot accuracy, and benchmark scores",
        ],
        "eligibility": "Open to all students",
        "description": "Prompt-engineering challenge.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "tech-quiz",
        "name": "Tech Quiz",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 2,
        "prize_amount": Decimal("10000"),
        "venue": "Gallery Hall",
        "fee": "₹200",
        "day": 2,
        "time": "10:00 AM – 5:00 PM",
        "rules": ["Teams of 2", "Written preliminary screening followed by live buzzer stage round"],
        "eligibility": "Open to all engineering and technology students",
        "description": "General technology knowledge rounds.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "workshop-day2",
        "name": "Workshop",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Gallery Hall",
        "fee": "Free Entry",
        "day": 2,
        "time": "10:00 AM – 11:00 AM",
        "rules": ["Morning technical workshop in Gallery Hall"],
        "eligibility": "Open to all delegates",
        "description": "Hands-on tech workshop.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "talk-session-physical",
        "name": "Talk Session: Physical...",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Gallery Hall",
        "fee": "Free Entry",
        "day": 2,
        "time": "11:00 AM – 1:00 PM",
        "rules": ["Keynote presentation followed by open floor debate"],
        "eligibility": "Open to all delegates",
        "description": "Physical ... debate — open floor.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "talk-agentic-ai",
        "name": "Talk: State of Agentic AI & Careers in Applied AI",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Gallery Hall",
        "fee": "Free Entry",
        "day": 2,
        "time": "2:00 PM – 3:30 PM",
        "rules": ["Keynote talk covering autonomous AI workflows and enterprise career trajectories"],
        "eligibility": "Open to all attendees",
        "description": "“State of Agentic AI & Careers in Applied AI” keynote.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "panel-cybersecurity",
        "name": "Panel: Cybersecurity Careers — Live CTF Debrief",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Gallery Hall",
        "fee": "Free Entry",
        "day": 2,
        "time": "4:00 PM – 5:00 PM",
        "rules": ["Live challenge walkthrough and industry career pathways panel"],
        "eligibility": "Open to all delegates",
        "description": "“Cybersecurity Careers — Live CTF Debrief” panel.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "debate-open-floor",
        "name": "Debate — Open Floor",
        "stream": EventStream.management,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Gallery Hall",
        "fee": "Free Entry",
        "day": 2,
        "time": "6:00 PM",
        "rules": ["Parliamentary debate format with audience participation"],
        "eligibility": "Open to all debaters",
        "description": "Debate — open floor.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "cultural-night",
        "name": "Cultural Night",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Open Air Stage",
        "fee": "Free Entry",
        "day": 2,
        "time": "4:00 PM – 7:00 PM",
        "rules": ["Showcase performances by Digital University Kerala student groups"],
        "eligibility": "Open to all attendees",
        "description": "By DUK students · Open Air Stage.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "dj-night",
        "name": "DJ Night",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Open Air Stage",
        "fee": "Free Entry",
        "day": 2,
        "time": "8:00 PM – 10:00 PM",
        "rules": ["Main stage electronic music set"],
        "eligibility": "All festival pass holders",
        "description": "High-octane electronic set on the Open Air Stage.",
        "featured": True,
        "status": "upcoming",
    },

    # ── DAY 3: NOVEMBER 1, 2026 ──
    {
        "slug": "ai-short-film",
        "name": "AI Short Film",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 4,
        "prize_amount": Decimal("10000"),
        "venue": "Gallery Hall",
        "fee": "FREE ENTRY",
        "day": 3,
        "time": "9:00 AM – 5:00 PM",
        "rules": [
            "All video, imagery, voiceover, and soundtrack must be generated using AI tools",
            "Screening and evaluation by creative media jury",
        ],
        "eligibility": "Open to creators across India",
        "description": "Theme-based short film, made entirely with AI tools. REG: FREE ENTRY.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "talk-kerala-startup-mission",
        "name": "Talk Session: Kerala Startup Mission",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Seminar Hall",
        "fee": "Free Entry",
        "day": 3,
        "time": "9:00 AM – 5:00 PM",
        "rules": ["Session by Kerala Startup Mission covering grants, incubation, and founder support"],
        "eligibility": "Open to student entrepreneurs",
        "description": "By Kerala Startup Mission.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "workshop-ethical-hacking",
        "name": "Ethical Hacking & OSINT Reconnaissance",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Gallery Hall",
        "fee": "Free Entry",
        "day": 3,
        "time": "10:00 AM – 1:00 PM",
        "rules": ["Bring your laptop with Kali Linux or VM environment configured", "Hands-on OSINT workflows"],
        "eligibility": "Open to all registered students",
        "description": "“Ethical Hacking & OSINT Reconnaissance: Think Like an Attacker”.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "valorant-tournament",
        "name": "Valorant Tournament",
        "stream": EventStream.gaming,
        "registration_type": RegistrationType.team,
        "team_size_min": 5,
        "team_size_max": 6,
        "prize_amount": Decimal("10000"),
        "venue": "Live / Online",
        "fee": "₹500",
        "day": 3,
        "time": "10:00 AM – 1:00 PM",
        "rules": [
            "Championship decider bracket",
            "Standard competitive 5v5 rules",
            "Live streaming on university main stage display",
        ],
        "eligibility": "Verified tournament squads",
        "description": "Championship decider · LIVE / ONLINE · REG: ₹500.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "hackathon-winners",
        "name": "Hackathon Winners & Prize Distribution",
        "stream": EventStream.tech,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Main Hall",
        "fee": "Hackathon Teams",
        "day": 3,
        "time": "1:00 PM",
        "rules": ["Closing of the 24HR Hackathon and trophy handover"],
        "eligibility": "All hackathon participants",
        "description": "Closing of the 24HR Hackathon.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "movie-quiz",
        "name": "Movie Quiz",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.team,
        "team_size_min": 2,
        "team_size_max": 2,
        "prize_amount": Decimal("5000"),
        "venue": "Gallery Hall",
        "fee": "₹200",
        "day": 3,
        "time": "1:00 PM – 3:00 PM",
        "rules": ["Teams of 2", "Multi-genre trivia across regional, national, and world cinema"],
        "eligibility": "Open to all film buffs",
        "description": "Trivia across genres & eras.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "fashion-show",
        "name": "Fashion Show",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.team,
        "team_size_min": 1,
        "team_size_max": 10,
        "prize_amount": Decimal("0"),
        "venue": "Open Air Stage",
        "fee": "OPEN CALL — NO REG FEE",
        "day": 3,
        "time": "6:00 PM – 7:00 PM",
        "rules": ["Student designers and models on the runway", "Open call runway briefing"],
        "eligibility": "Open to student designers and models",
        "description": "Student designers and models on the runway. OPEN CALL — NO REG FEE.",
        "featured": True,
        "status": "upcoming",
    },
    {
        "slug": "concert",
        "name": "Concert Night",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Open Air Stage",
        "fee": "Free Entry",
        "day": 3,
        "time": "7:00 PM – 10:00 PM",
        "rules": ["Festival grand finale headline concert on Open Air Stage"],
        "eligibility": "All festival pass holders",
        "description": "Closing night, Main Stage.",
        "featured": True,
        "status": "upcoming",
    },

    # ── PRE-FEST & ALL 3 DAYS ──
    {
        "slug": "e-football",
        "name": "E-Football Tournament",
        "stream": EventStream.gaming,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("5000"),
        "venue": "Online Qualifiers",
        "fee": "₹50/HEAD",
        "day": 1,
        "time": "5 Days Before",
        "rules": ["Single elimination knockout brackets played online"],
        "eligibility": "Open to all esports participants",
        "description": "Online qualifiers 5 days prior to main event.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "bgmi",
        "name": "BGMI Tournament",
        "stream": EventStream.gaming,
        "registration_type": RegistrationType.team,
        "team_size_min": 4,
        "team_size_max": 4,
        "prize_amount": Decimal("6000"),
        "venue": "Online Qualifiers",
        "fee": "₹50/HEAD",
        "day": 1,
        "time": "5 Days Before",
        "rules": ["Standard Battle Royale tournament rules", "Anti-cheat verification mandatory"],
        "eligibility": "Open to registered squads",
        "description": "Online qualifiers 5 days prior to main event.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "photography-videography",
        "name": "Photography & Videography",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("10000"),
        "venue": "Campus Wide",
        "fee": "₹100",
        "day": 1,
        "time": "All 3 Days",
        "rules": ["Theme revealed at festival start", "Entries submitted before festival close on Day 3"],
        "eligibility": "Open to all student creators",
        "description": "Campus-wide open contest across all 3 days.",
        "featured": False,
        "status": "upcoming",
    },
    {
        "slug": "food-court-markets",
        "name": "Food Court, Markets & Stalls",
        "stream": EventStream.culture,
        "registration_type": RegistrationType.solo,
        "prize_amount": Decimal("0"),
        "venue": "Campus Grounds",
        "fee": "Open Access",
        "day": 1,
        "time": "All 3 Days",
        "rules": ["Food stalls and merchandise vendors active throughout festival"],
        "eligibility": "All visitors and participants",
        "description": "Open all three days · Campus grounds.",
        "featured": False,
        "status": "upcoming",
    },
]

OFFICIAL_ANNOUNCEMENTS = [
    {
        "title": "DUK Technocity Gates Open for Fest Check-in",
        "content": "All registered operatives proceed to Gate 1 and Gate 2 for QR pass verification and welcome kit collection.",
        "category": "LOGISTICS",
        "urgent": True,
        "stream": "ALL",
        "pinned": True,
    },
    {
        "title": "Hackathon — 24HR Problem Statement Released",
        "content": "The official Agentic AI / Autonomous Systems hackathon challenge is now accessible in the build zone.",
        "category": "TECH",
        "urgent": False,
        "stream": "TECH",
        "pinned": False,
    },
    {
        "title": "Capture the Flag Briefing in Computer Lab",
        "content": "Registered CTF teams report to Computer Lab for network credential allocation and environment setup.",
        "category": "CYBER",
        "urgent": False,
        "stream": "TECH",
        "pinned": False,
    },
]

async def sync():
    async with SessionFactory() as db:
        print("Cleaning obsolete events...")
        # Remove old template events
        obsolete_slugs = [
            "robowars", "silent-circuit", "nritya", "street-battle", "street-art",
            "retro-arcade", "code-relay", "ai-arena", "pitch-perfect", "sustainability-hack",
            "battle-of-bands", "outreach-1000-hands", "climate-build", "impact-summit", "poetry-slam",
            "valorant", "hackathon-36", "ai-short-film-showcase", "campus-photography"
        ]
        from sqlalchemy import delete, or_
        await db.execute(delete(Event).where(Event.slug.in_(obsolete_slugs)))
        await db.execute(delete(Event).where(or_(
            Event.name.ilike('Robowars%'),
            Event.name.ilike('Silent Circuit%'),
            Event.name.ilike('Nritya%'),
            Event.name.ilike('Street Battle%'),
            Event.name.ilike('Retro Cabinet%')
        )))
        await db.commit()

        # Update or Insert official events
        print("Syncing official events from VYUHAM26_v8.pdf...")
        existing_result = await db.scalars(select(Event))
        existing_map = {e.slug: e for e in existing_result if e.slug}

        for ev_data in OFFICIAL_EVENTS:
            slug = ev_data["slug"]
            if slug in existing_map:
                ev = existing_map[slug]
                for k, v in ev_data.items():
                    setattr(ev, k, v)
            else:
                db.add(Event(**ev_data))

        # Sync announcements
        print("Syncing announcements...")
        await db.execute(delete(Announcement).where(Announcement.title.ilike('%National Hackathon%')))
        ann_result = await db.scalars(select(Announcement))
        existing_anns = {a.title: a for a in ann_result}

        for ann_data in OFFICIAL_ANNOUNCEMENTS:
            if ann_data["title"] not in existing_anns:
                db.add(Announcement(**ann_data))

        await db.commit()
        print("Database synchronized successfully with official schedule!")

    await engine.dispose()

if __name__ == "__main__":
    asyncio.run(sync())
